### ISSUE TITLE
Parser: acpi - When fully charged the 'until charged' is blank

### ISSUE THREAD

**Issue by borpin** [kellyjonbrazil/jc#144]
While charging the output of ACPI -V looks like;

```
#  jc acpi -V
[{"type": "Battery", "id": 0, "state": "Charging", "charge_percent": 20, "until_charged": "01:16:28", "design_capacity_mah": 2225, "last_full_capacity": 2135, "last_full_capacity_percent": 95}, {"type": "Adapter", "id": 0, "on-line": true}, {"type": "Thermal", "id": 0, "mode": "ok", "temperature": 49.0, "temperature_unit": "C", "trip_points": [{"id": 0, "switches_to_mode": "critical", "temperature": 127.0, "temperature_unit": "C"}, {"id": 1, "switches_to_mode": "hot", "temperature": 127.0, "temperature_unit": "C"}]}, {"type": "Cooling", "id": 0, "messages": ["Processor 0 of 10"]}, {"type": "Cooling", "id": 1, "messages": ["Processor 0 of 10"]}, {"type": "Cooling", "id": 2, "messages": ["x86_pkg_temp no state information available"]}, {"type": "Cooling", "id": 3, "messages": ["Processor 0 of 10"]}, {"type": "Cooling", "id": 4, "messages": ["intel_powerclamp no state information available"]}, {"type": "Cooling", "id": 5, "messages": ["Processor 0 of 10"]}]
```

Note the time in the *until_charged* element

Once charged
```
#  jc acpi -V
[{"type":"Battery","id":0,"state":"Charging","charge_percent":100,"until_charged":"until","design_capacity_mah":1946,"last_full_capacity":1867,"last_full_capacity_percent":95},{"type":"Adapter","id":0,"on-line":true},{"type":"Thermal","id":0,"mode":"ok","temperature":49.0,"temperature_unit":"C","trip_points":[{"id":0,"switches_to_mode":"critical","temperature":127.0,"temperature_unit":"C"},{"id":1,"switches_to_mode":"hot","temperature":127.0,"temperature_unit":"C"}]},{"type":"Cooling","id":0,"messages":["Processor 0 of 10"]},{"type":"Cooling","id":1,"messages":["Processor 0 of 10"]},{"type":"Cooling","id":2,"messages":["x86_pkg_temp no state information available"]},{"type":"Cooling","id":3,"messages":["Processor 0 of 10"]},{"type":"Cooling","id":4,"messages":["intel_powerclamp no state information available"]},{"type":"Cooling","id":5,"messages":["Processor 0 of 10"]}]
```
```
# acpi -V
Battery 0: Charging, 100%,  until charged
Battery 0: design capacity 1945 mAh, last full capacity 1867 mAh = 95%
Adapter 0: on-line
Thermal 0: ok, 49.0 degrees C
Thermal 0: trip point 0 switches to mode critical at temperature 127.0 degrees C
Thermal 0: trip point 1 switches to mode hot at temperature 127.0 degrees C
Cooling 0: Processor 0 of 10
Cooling 1: Processor 0 of 10
Cooling 2: x86_pkg_temp no state information available
Cooling 3: Processor 0 of 10
Cooling 4: intel_powerclamp no state information available
Cooling 5: Processor 0 of 10
root@pve:/usr/local/bin/monacpi#
```
Python

```
>>> import jc.parsers.acpi
>>> import subprocess
>>> result = subprocess.run(["acpi", "-V"], capture_output=True, text=True)
>>> data_out = jc.parsers.acpi.parse(result.stdout)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/jc/parsers/acpi.py", line 389, in parse
    return _process(raw_output)
  File "/usr/local/lib/python3.7/dist-packages/jc/parsers/acpi.py", line 275, in _process
    entry['until_charged_hours'] = int(entry['until_charged'].split(':')[0])
ValueError: invalid literal for int() with base 10: 'until'
>>>
```

**Comment by borpin** [comment]
Ah, this may be because I still have the local version of acpi.py. How do I get rid of that? Tried deleting it and just get an error when trying to run it.

I tried a pip3 forced update ` pip3 install --upgrade --force-reinstall jc`

```
#  jc acpi -V
Traceback (most recent call last):
  File "/usr/local/bin/jc", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/jc/cli.py", line 501, in main
    valid_command, run_command, magic_found_parser, magic_options = magic_parser(sys.argv)
  File "/usr/local/lib/python3.7/dist-packages/jc/cli.py", line 444, in magic_parser
    parser_info = about_jc()['parsers']
  File "/usr/local/lib/python3.7/dist-packages/jc/cli.py", line 284, in about_jc
    parser_mod = parser_module(parser)
  File "/usr/local/lib/python3.7/dist-packages/jc/cli.py", line 258, in parser_module
    return importlib.import_module(path + shortname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'jcparsers.acpi'
```

**Comment by borpin** [comment]
Close, the issue is that I had an old local version.
