### ISSUE TITLE
Remove local version of parser

### ISSUE THREAD

**Issue by borpin** [kellyjonbrazil/jc#145]
I have a local version of the acpi parser in ` .local/share/jc/jcparsers/`

How do I remove it and revert back to the installed version.

I tried deleting it but jc then complains it cannot find the parser.

I also cannot find the documentation about using local versions for testing.

**Comment by kellyjonbrazil** [comment]
Hi there - I’m going to take another look at that code because I noticed something similar where the local parser seemed to still be there even though I modified the .py extension. I think I ended up just completely deleting the file to fix it. You can also delete the cache folder but that shouldn’t affect anything. 

Can you confirm the issue is still happening if the file is deleted and not renamed?

Here is the documentation for the local parser feature: https://github.com/kellyjonbrazil/jc#custom-parsers

**Comment by kellyjonbrazil** [comment]
Yeah, it looks like I should do a check for the `.py` extension before attempting to load the local parser plugin, otherwise it will try to import any file it sees there. I'll work on this for the next release. in the mean-time, you must completely delete/remove the file from the `jcparsers` directory since just changing the extension won't work.
```
$ jc -h
Traceback (most recent call last):
  File "/Users/kbrazil/Library/Python/3.8/bin/jc", line 33, in <module>
    sys.exit(load_entry_point('jc', 'console_scripts', 'jc')())
  File "/Users/kbrazil/git/jc/jc/cli.py", line 537, in main
    print(help_doc(sys.argv))
  File "/Users/kbrazil/git/jc/jc/cli.py", line 370, in help_doc
    return helptext()
  File "/Users/kbrazil/git/jc/jc/cli.py", line 314, in helptext
    parsers_string = parsers_text(indent=12, pad=17)
  File "/Users/kbrazil/git/jc/jc/cli.py", line 266, in parsers_text
    parser_mod = parser_module(parser)
  File "/Users/kbrazil/git/jc/jc/cli.py", line 258, in parser_module
    return importlib.import_module(path + shortname)
  File "/usr/local/Cellar/python@3.8/3.8.9/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'jcparsers.test'
```

**Comment by borpin** [comment]
Ok, Thanks :)

**Comment by kellyjonbrazil** [comment]
Hi there - I uploaded v1.15.6 to PyPi, so you should be able to download it with `pip` now. It should address this issue where someone renames a parser plugin to `parser_name.py.old`. Now `jc` will look to see if the `.py` part is at the end of the filename, not just in the filename somewhere.
