### ISSUE TITLE
Impossible to parse ping command result

### ISSUE THREAD

**Issue by julienbriault** [kellyjonbrazil/jc#200]
Here's the resulting message:
```
 ✘ pil0t@cockpit  ~   main  ping -c 1 localhost | jc --ping -d
Traceback (most recent call last):
  File "/home/pil0t/.local/bin/jc", line 8, in <module>
    sys.exit(main())
  File "/home/pil0t/.local/lib/python3.10/site-packages/jc/cli.py", line 540, in main
    result = parser.parse(data, raw=raw, quiet=quiet)
  File "/home/pil0t/.local/lib/python3.10/site-packages/jc/parsers/ping.py", line 640, in parse
    raw_output = _linux_parse(data)
  File "/home/pil0t/.local/lib/python3.10/site-packages/jc/parsers/ping.py", line 348, in _linux_parse
    split_line = line.split(' = ')[1]
IndexError: list index out of range
```

**Comment by kellyjonbrazil** [comment]
Hi - thank you for reporting this!

Could you paste the ping output before it gets to jc? What distro/version is this on. Also, have you tried setting to C locale?

**Comment by julienbriault** [comment]
It works!
