### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by elkarouh** [kellyjonbrazil/jc#214]
Is it possible to add the 'top' command?

Keep up the good work !

**Comment by kellyjonbrazil** [comment]
Hi there - thanks for the feature request! 

I have looked into adding a `top` parser, but since `top` is an interactive command there isn't a good way to get the data to `jc`.

Also, `jc` has parsers for other commands that provide similar output (`ps`, `free`, etc.), so  I have decided not to create one for `top`.

Thanks for enjoying `jc`!

**Comment by elkarouh** [comment]
Top can be run in batch mode:

top -b -n 1

**Comment by kellyjonbrazil** [comment]
Very cool - I didn't realize there was a batch option. Looks like it is linux-only, but that is fine:
```
$ top -b -n 2
top - 10:43:42 up 1 min,  2 users,  load average: 0.44, 0.18, 0.07
Tasks: 111 total,   2 running, 109 sleeping,   0 stopped,   0 zombie
%Cpu(s):  5.9 us,  5.9 sy,  0.0 ni, 88.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  3861332 total,  3448864 free,   217100 used,   195368 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used.  3420500 avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
     1 root      20   0  128056   6680   4204 S  0.0  0.2   0:02.07 systemd
     2 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kthreadd
     3 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kworker/0:0
     4 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/0:0H
     5 root      20   0       0      0      0 S  0.0  0.0   0:00.02 kworker/u256:0
     6 root      20   0       0      0      0 S  0.0  0.0   0:00.04 ksoftirqd/0
     7 root      rt   0       0      0      0 S  0.0  0.0   0:00.00 migration/0
     8 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcu_bh
     9 root      20   0       0      0      0 R  0.0  0.0   0:00.40 rcu_sched
    10 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 lru-add-drain
    11 root      rt   0       0      0      0 S  0.0  0.0   0:00.00 watchdog/0
    13 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kdevtmpfs
    14 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 netns
    15 root      20   0       0      0      0 S  0.0  0.0   0:00.00 khungtaskd
    16 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 writeback
    17 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kintegrityd
    18 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset
    19 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset
    20 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset
    21 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kblockd
    22 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 md
    23 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 edac-poller
    24 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 watchdogd
    25 root      20   0       0      0      0 S  0.0  0.0   0:00.24 kworker/0:1
    30 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kswapd0
    31 root      25   5       0      0      0 S  0.0  0.0   0:00.00 ksmd
    32 root      39  19       0      0      0 S  0.0  0.0   0:00.00 khugepaged
    33 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 crypto
    41 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kthrotld
    42 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kworker/u256:1
    43 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kmpath_rdacd
    44 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kaluad
    45 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kpsmoused
    46 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kworker/0:2
    47 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 ipv6_addrconf
    60 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 deferwq
    95 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kauditd
   121 root      20   0       0      0      0 S  0.0  0.0   0:00.01 kworker/0:3
   272 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 nfit
   273 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 mpt_poll_0
   274 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 mpt/0
   275 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 ata_sff
   302 root      20   0       0      0      0 S  0.0  0.0   0:00.00 scsi_eh_0
   308 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 scsi_tmf_0
   334 root      20   0       0      0      0 S  0.0  0.0   0:00.01 kworker/u256:2
   335 root      20   0       0      0      0 S  0.0  0.0   0:00.01 scsi_eh_1
   338 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 scsi_tmf_1
   345 root      20   0       0      0      0 S  0.0  0.0   0:00.01 scsi_eh_2
   347 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 scsi_tmf_2
   348 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kworker/u256:3
   356 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kworker/u256:4
   359 root     -51   0       0      0      0 S  0.0  0.0   0:00.01 irq/16-vmwgfx
   360 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 ttm_swap
   380 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/0:1H
   432 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kdmflush
   433 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset
   442 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kdmflush
   443 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset
   456 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset
   457 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfsalloc
   458 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs_mru_cache
   459 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-buf/dm-0
   460 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-data/dm-0
   461 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-conv/dm-0
   462 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-cil/dm-0
   463 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-reclaim/dm-
   464 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-log/dm-0
   465 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-eofblocks/d
   466 root      20   0       0      0      0 S  0.0  0.0   0:00.04 xfsaild/dm-0
   543 root      20   0   39080   3080   2760 S  0.0  0.1   0:00.16 systemd-journal
   565 root      20   0  201124   4180   2608 S  0.0  0.1   0:00.01 lvmetad
   577 root      20   0   48124   5332   2876 S  0.0  0.1   0:00.23 systemd-udevd
   650 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/u257:0
   653 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 hci0
   654 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 hci0
   655 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/u257:1
   658 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/u257:2
   721 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-buf/sda1
   722 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-data/sda1
   723 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-conv/sda1
   724 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-cil/sda1
   725 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-reclaim/sda
   727 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-log/sda1
   729 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-eofblocks/s
   730 root      20   0       0      0      0 S  0.0  0.0   0:00.00 xfsaild/sda1
   751 root      16  -4   55528    884    484 S  0.0  0.0   0:00.01 auditd
   775 root      20   0   57524   2576   2128 S  0.0  0.1   0:00.01 bluetoothd
   776 root      20   0   52808   2740   1984 S  0.0  0.1   0:00.03 smartd
   777 polkitd   20   0  613016  15044   4904 S  0.0  0.4   0:00.17 polkitd
   780 root      20   0   26420   1796   1472 S  0.0  0.0   0:00.02 systemd-logind
   788 dbus      20   0   66472   2428   1848 S  0.0  0.1   0:00.12 dbus-daemon
   799 chrony    20   0  117804   1724   1296 S  0.0  0.0   0:00.01 chronyd
   829 root      20   0  126292   1676   1048 S  0.0  0.0   0:00.44 crond
   846 root      20   0  358752  29532   7048 S  0.0  0.8   0:00.78 firewalld
   877 root      20   0   96572   2532   1872 S  0.0  0.1   0:00.16 login
   878 root      20   0  110108    868    736 S  0.0  0.0   0:00.01 agetty
   879 root      20   0  832784   9072   6884 S  0.0  0.2   0:00.15 NetworkManager
  1029 root      20   0  102896   5472   3412 S  0.0  0.1   0:00.04 dhclient
  1221 root      20   0  574204  17428   6128 S  0.0  0.5   0:00.20 tuned
  1222 root      20   0  112920   4316   3288 S  0.0  0.1   0:00.02 sshd
  1223 root      20   0  578768  30972  13320 S  0.0  0.8   0:00.37 dockerd-current
  1225 root      20   0  218548   4124   3280 S  0.0  0.1   0:00.10 rsyslogd
  1306 root      20   0  219104  10632   5364 S  0.0  0.3   0:00.11 docker-containe
  1495 root      20   0   89700   2160   1124 S  0.0  0.1   0:00.01 master
  1505 postfix   20   0   89872   4080   3080 S  0.0  0.1   0:00.00 qmgr
  1859 kbrazil   20   0  115712   2384   1632 S  0.0  0.1   0:00.01 bash
  1884 root      20   0  158924   5696   4356 S  0.0  0.1   0:00.17 sshd
  1886 postfix   20   0   89804   4060   3060 S  0.0  0.1   0:00.00 pickup
  1889 kbrazil   20   0  158924   2444   1088 S  0.0  0.1   0:00.01 sshd
  1890 kbrazil   20   0  115580   2140   1636 S  0.0  0.1   0:00.00 bash
  1908 kbrazil   20   0  161888   2100   1520 R  0.0  0.1   0:00.00 top

top - 10:43:45 up 1 min,  2 users,  load average: 0.40, 0.18, 0.06
Tasks: 111 total,   2 running, 109 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  3861332 total,  3448756 free,   217208 used,   195368 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used.  3420392 avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
    25 root      20   0       0      0      0 R  0.3  0.0   0:00.25 kworker/0:1
   466 root      20   0       0      0      0 S  0.3  0.0   0:00.05 xfsaild/dm-0
  1908 kbrazil   20   0  161892   2140   1540 R  0.3  0.1   0:00.01 top
     1 root      20   0  128056   6680   4204 S  0.0  0.2   0:02.07 systemd
     2 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kthreadd
     3 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kworker/0:0
     4 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/0:0H
     5 root      20   0       0      0      0 S  0.0  0.0   0:00.02 kworker/u256:0
     6 root      20   0       0      0      0 S  0.0  0.0   0:00.04 ksoftirqd/0
     7 root      rt   0       0      0      0 S  0.0  0.0   0:00.00 migration/0
     8 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcu_bh
     9 root      20   0       0      0      0 S  0.0  0.0   0:00.40 rcu_sched
    10 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 lru-add-drain
    11 root      rt   0       0      0      0 S  0.0  0.0   0:00.00 watchdog/0
    13 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kdevtmpfs
    14 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 netns
    15 root      20   0       0      0      0 S  0.0  0.0   0:00.00 khungtaskd
    16 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 writeback
    17 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kintegrityd
    18 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset
    19 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset
    20 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset
    21 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kblockd
    22 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 md
    23 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 edac-poller
    24 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 watchdogd
    30 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kswapd0
    31 root      25   5       0      0      0 S  0.0  0.0   0:00.00 ksmd
    32 root      39  19       0      0      0 S  0.0  0.0   0:00.00 khugepaged
    33 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 crypto
    41 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kthrotld
    42 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kworker/u256:1
    43 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kmpath_rdacd
    44 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kaluad
    45 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kpsmoused
    46 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kworker/0:2
    47 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 ipv6_addrconf
    60 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 deferwq
    95 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kauditd
   121 root      20   0       0      0      0 S  0.0  0.0   0:00.01 kworker/0:3
   272 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 nfit
   273 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 mpt_poll_0
   274 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 mpt/0
   275 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 ata_sff
   302 root      20   0       0      0      0 S  0.0  0.0   0:00.00 scsi_eh_0
   308 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 scsi_tmf_0
   334 root      20   0       0      0      0 S  0.0  0.0   0:00.01 kworker/u256:2
   335 root      20   0       0      0      0 S  0.0  0.0   0:00.01 scsi_eh_1
   338 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 scsi_tmf_1
   345 root      20   0       0      0      0 S  0.0  0.0   0:00.01 scsi_eh_2
   347 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 scsi_tmf_2
   348 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kworker/u256:3
   356 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kworker/u256:4
   359 root     -51   0       0      0      0 S  0.0  0.0   0:00.01 irq/16-vmwgfx
   360 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 ttm_swap
   380 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/0:1H
   432 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kdmflush
   433 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset
   442 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kdmflush
   443 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset
   456 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 bioset
   457 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfsalloc
   458 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs_mru_cache
   459 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-buf/dm-0
   460 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-data/dm-0
   461 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-conv/dm-0
   462 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-cil/dm-0
   463 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-reclaim/dm-
   464 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-log/dm-0
   465 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-eofblocks/d
   543 root      20   0   39080   3080   2760 S  0.0  0.1   0:00.16 systemd-journal
   565 root      20   0  201124   4180   2608 S  0.0  0.1   0:00.01 lvmetad
   577 root      20   0   48124   5332   2876 S  0.0  0.1   0:00.23 systemd-udevd
   650 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/u257:0
   653 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 hci0
   654 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 hci0
   655 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/u257:1
   658 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/u257:2
   721 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-buf/sda1
   722 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-data/sda1
   723 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-conv/sda1
   724 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-cil/sda1
   725 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-reclaim/sda
   727 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-log/sda1
   729 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs-eofblocks/s
   730 root      20   0       0      0      0 S  0.0  0.0   0:00.00 xfsaild/sda1
   751 root      16  -4   55528    884    484 S  0.0  0.0   0:00.01 auditd
   775 root      20   0   57524   2576   2128 S  0.0  0.1   0:00.01 bluetoothd
   776 root      20   0   52808   2740   1984 S  0.0  0.1   0:00.03 smartd
   777 polkitd   20   0  613016  15044   4904 S  0.0  0.4   0:00.17 polkitd
   780 root      20   0   26420   1796   1472 S  0.0  0.0   0:00.02 systemd-logind
   788 dbus      20   0   66472   2428   1848 S  0.0  0.1   0:00.12 dbus-daemon
   799 chrony    20   0  117804   1724   1296 S  0.0  0.0   0:00.01 chronyd
   829 root      20   0  126292   1676   1048 S  0.0  0.0   0:00.44 crond
   846 root      20   0  358752  29532   7048 S  0.0  0.8   0:00.78 firewalld
   877 root      20   0   96572   2532   1872 S  0.0  0.1   0:00.16 login
   878 root      20   0  110108    868    736 S  0.0  0.0   0:00.01 agetty
   879 root      20   0  832784   9072   6884 S  0.0  0.2   0:00.15 NetworkManager
  1029 root      20   0  102896   5472   3412 S  0.0  0.1   0:00.04 dhclient
  1221 root      20   0  574204  17428   6128 S  0.0  0.5   0:00.20 tuned
  1222 root      20   0  112920   4316   3288 S  0.0  0.1   0:00.02 sshd
  1223 root      20   0  578768  30972  13320 S  0.0  0.8   0:00.37 dockerd-current
  1225 root      20   0  218548   4124   3280 S  0.0  0.1   0:00.10 rsyslogd
  1306 root      20   0  219104  10848   5364 S  0.0  0.3   0:00.11 docker-containe
  1495 root      20   0   89700   2160   1124 S  0.0  0.1   0:00.01 master
  1505 postfix   20   0   89872   4080   3080 S  0.0  0.1   0:00.00 qmgr
  1859 kbrazil   20   0  115712   2384   1632 S  0.0  0.1   0:00.01 bash
  1884 root      20   0  158924   5696   4356 S  0.0  0.1   0:00.17 sshd
  1886 postfix   20   0   89804   4060   3060 S  0.0  0.1   0:00.00 pickup
  1889 kbrazil   20   0  158924   2444   1088 S  0.0  0.1   0:00.01 sshd
  1890 kbrazil   20   0  115580   2140   1636 S  0.0  0.1   0:00.00 bash
```
I could probably do something with that. Have you checked out `pidstat`? I think it outputs similar information and `jc` already has a parser for it.

**Comment by elkarouh** [comment]
Hi,

I didn't know about pidstat. Seems to be a cool alternative.

Regards.

**Comment by kellyjonbrazil** [comment]
Hi @elkarouh,

I have a working version of the `top -b` parser that can be tested by copy/pasting the [code here](https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/top.py) to a file named `top.py` in your [parser plugin directory](https://github.com/kellyjonbrazil/jc#custom-parsers). I would love to see if it works for you or if you run into any issues.

If this works well, I also plan on creating a streaming version of this parser, since `top -b` output can go on infinitely.

Thanks!

**Comment by elkarouh** [comment]
[07:30:25]  $jc -d top -b -n 3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "jc.cli", line 520, in main
  File "/auto/home/karouh/.local/share/jc/jcparsers/top.py", line 616, in
parse
    return raw_output if raw else _process(raw_output, quiet=quiet)
  File "/auto/home/karouh/.local/share/jc/jcparsers/top.py", line 433, in
_process
    for p_idx, proc in enumerate(item['processes']):
KeyError: 'processes'
[07:31:23]  $uname -a
Linux dhws149 3.10.0-1160.31.1.el7.x86_64 #1 SMP Wed May 26 20:18:08 UTC
2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kellyjonbrazil** [comment]
Thanks for testing! Could you copy/paste the `top` output so I can try to replicate? Also, what version of `jc` are you running?

**Comment by kellyjonbrazil** [comment]
@elkarouh I also added a streaming version (`top-s`) [here](https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/top_s.py) if you would like to test.

Thanks!

**Comment by kellyjonbrazil** [comment]
added in v1.20.0

**Comment by elkarouh** [comment]
It works!
