### ISSUE TITLE
Allow duplicate keys in Key/Value parser

### ISSUE THREAD

**Issue by kellyjonbrazil** [kellyjonbrazil/jc#219]
The **Key/Value** (`--kv`) parser will fail if there are duplicate keys in the input. It might be desired to allow duplicate keys with one of the following behaviors:

1.  Only use the last duplicate key's value
2. Slurp all of the duplicate keys' values into a list

Some ideas here:
https://stackoverflow.com/questions/30095471/configparser-duplicate-keys-in-python

or maybe just use `strict=False` in configparser?
https://python.readthedocs.io/en/latest/library/configparser.html

**Comment by kellyjonbrazil** [comment]
Here is an example use-case of the **Key/Value** parser failing with duplicate keys:
```
$ curl --silent --header "origin: https://origin.example.com" --request GET "https://cors-test.appspot.com/test" --head | grep -e ":" | jc --kv -d
Traceback (most recent call last):
  File "/Users/kbrazil/git/jc/jc/parsers/ini.py", line 140, in parse
    ini.read_string(data)
  File "/usr/local/Cellar/python@3.8/3.8.9/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 723, in read_string
    self.read_file(sfile, source)
  File "/usr/local/Cellar/python@3.8/3.8.9/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/local/Cellar/python@3.8/3.8.9/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 1082, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '<string>', line: 1
'cache-control: no-cache\r\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kbrazil/Library/Python/3.8/bin/jc", line 33, in <module>
    sys.exit(load_entry_point('jc', 'console_scripts', 'jc')())
  File "/Users/kbrazil/git/jc/jc/cli.py", line 520, in main
    result = parser.parse(data,
  File "/Users/kbrazil/git/jc/jc/parsers/kv.py", line 83, in parse
    return jc.parsers.ini.parse(data, raw=raw, quiet=quiet)
  File "/Users/kbrazil/git/jc/jc/parsers/ini.py", line 145, in parse
    ini.read_string(data)
  File "/usr/local/Cellar/python@3.8/3.8.9/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 723, in read_string
    self.read_file(sfile, source)
  File "/usr/local/Cellar/python@3.8/3.8.9/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/local/Cellar/python@3.8/3.8.9/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 1093, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '<string>' [line  3]: option 'cache-control' in section 'data' already exists
```

**Comment by kellyjonbrazil** [comment]
Fixed in `dev`. Using `strict=False` in configparser library to allow duplicate keys and only the last value is kept.

**Comment by kellyjonbrazil** [comment]
I'm going to release this now in the v1.18.7 release on PIP-only. If things test ok, then I'll bump the github release as well. Thanks!
