### ISSUE TITLE
yaml: Object of type 'datetime' is not JSON serializable

### ISSUE THREAD

**Issue by misterikkit** [kellyjonbrazil/jc#229]
Attempting to use `jc --yaml` with kubernetes manifests failed because those manifests included datetime objects. See below.

    jc version 1.18.2
    Python 3.6.15

```
 $ echo 'deploymentTime: 2022-04-18T11:12:47' | jc --yaml -d
Traceback (most recent call last):
  File "/home/jbasseri/.local/bin/jc", line 8, in <module>
    sys.exit(main())
  File "/home/jbasseri/.local/lib/python3.6/site-packages/jc/cli.py", line 511, in main
    piped_out=piped_output(force_color)),
  File "/home/jbasseri/.local/lib/python3.6/site-packages/jc/cli.py", line 269, in json_out
    return str(highlight(json.dumps(data, indent=indent, separators=separators, ensure_ascii=False),
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable
```

**Comment by kellyjonbrazil** [comment]
Thanks for reporting this! I should be able to fix this. Not sure if there is an option in the YAML library to auto convert these or maybe I can create a recursive function to walk the dictionary and convert the timestamps. I'll look into it.

**Comment by kellyjonbrazil** [comment]
I have checked in a fix in the `dev` branch.

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/yaml.py

You can test by copy/pasting the `yaml.py` file to the [plugin directory](https://github.com/kellyjonbrazil/jc#custom-parsers), which will override the built-in YAML parser.

Could you let me know if that works for you? If so, this will go into v1.18.7.

**Comment by kellyjonbrazil** [comment]
I'm going to release this now in the v1.18.7 release on PIP-only. If things test ok, then I'll bump the github release as well. Thanks!
