### ISSUE TITLE
Problem parsing multiline licenses with the pip show parser

### ISSUE THREAD

**Issue by bryder** [kellyjonbrazil/jc#243]
Hi,
Thanks for the great work on jc.

We've come across a few packages with multiline license which fail in the pip show parser for jc

```
pip show cppy | jc --pip-show -dd
IndexError
Python 3.7.7: /usr/home/bryder/bin/jc.exe
Mon May 16 14:51:08 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /usr/home/bryder/<string> in <module>()


 /usr/home/bryder/jc.cli in main()


 /usr/home/bryder/jc.parsers.pip_show in parse(data='Name: cppy\nVersion: 1.2.1\nSummary: UNKNOWN\nHome-...python3.7/site-packages\nRequires: \nRequired-by: \n', raw=False, quiet=False)

IndexError: list index out of range
    __cause__ = None
    __class__ = <class 'IndexError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of IndexError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of IndexError object>
    __doc__ = 'Sequence index out of range.'
    __eq__ = <method-wrapper '__eq__' of IndexError object>
    __format__ = <built-in method __format__ of IndexError object>
    __ge__ = <method-wrapper '__ge__' of IndexError object>
    __getattribute__ = <method-wrapper '__getattribute__' of IndexError object>
    __gt__ = <method-wrapper '__gt__' of IndexError object>
    __hash__ = <method-wrapper '__hash__' of IndexError object>
    __init__ = <method-wrapper '__init__' of IndexError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of IndexError object>
    __lt__ = <method-wrapper '__lt__' of IndexError object>
    __ne__ = <method-wrapper '__ne__' of IndexError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of IndexError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of IndexError object>
    __repr__ = <method-wrapper '__repr__' of IndexError object>
    __setattr__ = <method-wrapper '__setattr__' of IndexError object>
    __setstate__ = <built-in method __setstate__ of IndexError object>
    __sizeof__ = <built-in method __sizeof__ of IndexError object>
    __str__ = <method-wrapper '__str__' of IndexError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('list index out of range',)
    with_traceback = <built-in method with_traceback of IndexError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "jc.cli", line 457, in main
    result = parser.parse(data, raw=raw, quiet=quiet)
  File "jc.parsers.pip_show", line 131, in parse
    item_value = row.split(': ', maxsplit=1)[1]
IndexError: list index out of range

```

The same problem occurs with kiwisolver

It appears to be because they have a multiline license
```
pip show cppy
Name: cppy
Version: 1.2.1
Summary: UNKNOWN
Home-page: https://github.com/nucleic/cppy
Author: None
Author-email: The Nucleic Development Team <sccolbert@gmail.com>
License: Copyright (c) 2014, Nucleic
        All rights reserved.        
        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions are met:        
        * Redistributions of source code must retain the above copyright notice, this
          list of conditions and the following disclaimer.        
        * Redistributions in binary form must reproduce the above copyright notice,
          this list of conditions and the following disclaimer in the documentation
          and/or other materials provided with the distribution.        
        * Neither the name of the copyright holder nor the names of its
          contributors may be used to endorse or promote products derived from
          this software without specific prior written permission.        
        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
        AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
        IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
        DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
        FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
        DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
        SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
        CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
        OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
        OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.        
Location: /usr/home/bryder/.local/lib/python3.7/site-packages
Requires: 
Required-by: 
```

**Comment by kellyjonbrazil** [comment]
Hi - thanks for reporting this. This shouldn't be too hard to fix. I can pull all of the license text into a single string using `\n` for line breaks unless you think we should only keep the first line of the license?

Thanks!

**Comment by bryder** [comment]
Definitely keep the full license please using \n for line breaks.

I'm used that that kind of thing in json for multiline strings.

**Comment by kellyjonbrazil** [comment]
I have a fix that is ready for testing. You can copy/paste the [`pip-show.py`](https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/pip_show.py) file in the `dev` branch to your [plugin directory](https://github.com/kellyjonbrazil/jc/tree/master#custom-parsers) to see if it works for you. If all is good, I can get this in the next release.

Thanks!

**Comment by kellyjonbrazil** [comment]
Spoke too soon - I see a bug where it is leaving out the first line of the license. Should be a quick fix...

**Comment by kellyjonbrazil** [comment]
Ok, I think we are good to go now. Let me know if you run into any issues.

Thanks!

**Comment by bryder** [comment]
Works great thanks! I look forward to the release (since I'm lazy and usually use the binary)

**Comment by kellyjonbrazil** [comment]
Excellent! The plugin parsers should work with the binary, too.

**Comment by kellyjonbrazil** [comment]
Fix is in v1.20.0
