### ISSUE TITLE
Problem parsing date from systemctl

### ISSUE THREAD

**Issue by chriscroome** [kellyjonbrazil/jc#324]
I've written [a Bash script](https://git.coop/webarch/scripts/-/blob/master/bin/check-cert-restart-service.sh) to check the date a cert is valid from and compare that with the date that a service has been running for and then restart the service is the cert has been renewed since the service started.

On most Debian Bullseye servers I have run this on there hasn't been a problem, but on the two oldest (ones that have been upgraded many times) this command fails:

```bash
systemctl show exim4 | jc -q -m --ini | jp -c -u ActiveEnterTimestamp | jc -q -m --date
```

Getting the date when Exim was started works:

```bash
systemctl show exim4 | jc -q -m --ini | jp -c -u ActiveEnterTimestamp
Mon 2022-10-17 21:51:56 BST
```

But parsing that date fails:

```bash
ystemctl show exim4 | jc -q -m --ini | jp -c -u ActiveEnterTimestamp | jc -q -m --date -dd
AttributeError
Python 3.9.2: /usr/bin/python3
Wed Nov 23 23:33:12 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /usr/local/bin/jc in <module>()
    1 #!/usr/bin/python3
    2 # -*- coding: utf-8 -*-
    3 import re
    4 import sys
    5 from jc.cli import main
    6 if __name__ == '__main__':
    7     sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    8     sys.exit(main())
sys = <module 'sys' (built-in)>
sys.exit = <built-in function exit>
main = <function main>

 /usr/local/lib/python3.9/dist-packages/jc/cli.py in main()
  758                 f'{e.__class__.__name__}: {e}'
  759             ])
  760             self.exit_error()
  761 
  762 
  763 def main():
  764     JcCli().run()
  765 
  766 
  767 if __name__ == '__main__':
  768     main()
global JcCli = <class 'jc.cli.JcCli'>
).run = <function JcCli.run>


 /usr/local/lib/python3.9/dist-packages/jc/cli.py in run(self=<jc.cli.JcCli object>)
  741                 ])
  742                 self.exit_error()
  743 
  744     def run(self) -> None:
  745         try:
  746             self._run()
  747 
  748         except KeyboardInterrupt:
  749             utils.error_message(['Exit due to SIGINT.'])
  750             self.exit_error()
  751 
self = <jc.cli.JcCli object>
self._run = <bound method JcCli._run of <jc.cli.JcCli object>>

 /usr/local/lib/python3.9/dist-packages/jc/cli.py in _run(self=<jc.cli.JcCli object>)
  705                 if _parser_is_streaming(self.parser_module):
  706                     self.streaming_parse_and_print()
  707                     self.exit_clean()
  708 
  709                 else:
  710                     self.standard_parse_and_print()
  711                     self.exit_clean()
  712 
  713             except BrokenPipeError:
  714                 sys.stdout = None  # type: ignore
  715 
self = <jc.cli.JcCli object>
self.standard_parse_and_print = <bound method JcCli.standard_parse_and_print of <jc.cli.JcCli object>>


 /usr/local/lib/python3.9/dist-packages/jc/cli.py in standard_parse_and_print(self=<jc.cli.JcCli object>)
  562                 self.data_in = self.data_in.decode('utf-8')
  563         except UnicodeDecodeError:
  564             pass
  565 
  566         if self.parser_module:
  567             self.data_out = self.parser_module.parse(
  568                 self.data_in,
  569                 raw=self.raw,
  570                 quiet=self.quiet
  571             )
  572 
self = <jc.cli.JcCli object>
self.data_out = None
self.parser_module = <module 'jc.parsers.date' from '/usr/local/lib/python3.9/dist-packages/jc/parsers/date.py'>
self.parser_module.parse = <function parse>
self.data_in = 'Mon 2022-10-17 21:51:56 BST\n'
raw undefined
self.raw = False
quiet undefined
self.quiet = True


 /usr/local/lib/python3.9/dist-packages/jc/parsers/date.py in parse(data='Mon 2022-10-17 21:51:56 BST\n', raw=False, quiet=True)
  171 
  172         if dt_utc:
  173             dt = dt_utc
  174 
  175         raw_output = {
  176             'year': dt.year,
  177             'month': dt.strftime('%b'),
  178             'month_num': dt.month,
  179             'day': dt.day,
  180             'weekday': dt.strftime('%a'),
  181             'weekday_num': dt.isoweekday(),
dt = None
dt.year undefined
AttributeError: 'NoneType' object has no attribute 'year'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'NoneType' object has no attribute 'year'",)
    with_traceback = <built-in method with_traceback of AttributeError object>


The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/local/bin/jc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/jc/cli.py", line 764, in main
    JcCli().run()
  File "/usr/local/lib/python3.9/dist-packages/jc/cli.py", line 746, in run
    self._run()
  File "/usr/local/lib/python3.9/dist-packages/jc/cli.py", line 710, in _run
    self.standard_parse_and_print()
  File "/usr/local/lib/python3.9/dist-packages/jc/cli.py", line 567, in standard_parse_and_print
    self.data_out = self.parser_module.parse(
  File "/usr/local/lib/python3.9/dist-packages/jc/parsers/date.py", line 176, in parse
    'year': dt.year,
AttributeError: 'NoneType' object has no attribute 'year'
```

Is this an issue with the date / time configuration of the server or a issue with the JC date parser?

**Comment by chriscroome** [comment]
Sorry for the noise -- the [fix is to set the server to use UTC](https://unix.stackexchange.com/a/447989).

**Comment by kellyjonbrazil** [comment]
Hi @chriscroome!

This is because the locale of the server outputting that `date` string is not in `C` or `en_US.UTF-8`. The `date` output should look like this:
```
Wed Nov 23 16:00:15 PST 2022
```
instead of this:
```
Mon 2022-10-17 21:51:56 BST
```
Is there a way to change the locale on those servers before running date? e.g. `LC_ALL=C date`

**Comment by chriscroome** [comment]
Yes, sorry I worked that out soon after posting this :roll_eyes: Thanks!
