### ISSUE TITLE
netstat parser crashes for programs on UDP containing space

### ISSUE THREAD

**Issue by HervisDaubeny** [kellyjonbrazil/jc#446]
Today I encountered an error while running the following command:
```
root@double-logger-testing:~# netstat -tupln | jc -d --netstat -p
Traceback (most recent call last):
  File "/usr/local/bin/jc", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/jc/cli.py", line 890, in main
    JcCli().run()
  File "/usr/local/lib/python3.7/dist-packages/jc/cli.py", line 872, in run
    self._run()
  File "/usr/local/lib/python3.7/dist-packages/jc/cli.py", line 836, in _run
    self.standard_parse_and_print()
  File "/usr/local/lib/python3.7/dist-packages/jc/cli.py", line 734, in standard_parse_and_print
    quiet=self.quiet
  File "/usr/local/lib/python3.7/dist-packages/jc/parsers/netstat.py", line 459, in parse
    raw_output = jc.parsers.netstat_linux.parse(cleandata)
  File "/usr/local/lib/python3.7/dist-packages/jc/parsers/netstat_linux.py", line 280, in parse
    return parse_post(raw_output)
  File "/usr/local/lib/python3.7/dist-packages/jc/parsers/netstat_linux.py", line 123, in parse_post
    name = entry['program_name'].split('/', maxsplit=1)[1]
IndexError: list index out of range
```

After some testing I found out, that `jc` crashes if this program is contained in the netstat command output:
```
root@double-logger-testing:~# netstat -tupln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           442/avahi-daemon: r
udp        0      0 0.0.0.0:49926           0.0.0.0:*                           442/avahi-daemon: r
udp6       0      0 :::5353                 :::*                                442/avahi-daemon: r
udp6       0      0 :::35569                :::*                                442/avahi-daemon: r
```

After some digging in source code I found and error in the method `parse_network()` in `jc/parsers/netstat_linux.py`.
The problem is, that all programs running on UDP protocol always have the field "State" empty. What happens when the "PID/Program name" contains space is, another split which leads to first part of the name being put in "State" column an the other to "PID/Program name". The secon column is then being split by `'/'` which causes the error. (Because the part containing the `/` is stuffed to "State" column.)

In the example I provided:
```
{'proto': 'udp', 'recv_q': '0', 'send_q': '0', 'local_address': '0.0.0.0:5353', 'foreign_address': '0.0.0.0:*', 'state': '442/avahi-daemon:', 'program_name': 'r ', 'kind': 'network'}
{'proto': 'udp', 'recv_q': '0', 'send_q': '0', 'local_address': '0.0.0.0:49926', 'foreign_address': '0.0.0.0:*', 'state': '442/avahi-daemon:', 'program_name': 'r ', 'kind': 'network'}
{'proto': 'udp6', 'recv_q': '0', 'send_q': '0', 'local_address': ':::5353', 'foreign_address': ':::*', 'state': '442/avahi-daemon:', 'program_name': 'r ', 'kind': 'network'}
{'proto': 'udp6', 'recv_q': '0', 'send_q': '0', 'local_address': ':::35569', 'foreign_address': ':::*', 'state': '442/avahi-daemon:', 'program_name': 'r ', 'kind': 'network'}
```
*I got this output by calling* `print(ouptut_line)` *just before return in the method* `parse_network()`.

**Comment by kellyjonbrazil** [comment]
Thanks for reporting this and for the fix. I should have some time to take a look at this in a few days and get the fix into the next release.

**Comment by kellyjonbrazil** [comment]
@HervisDaubeny It looks like your fix in https://github.com/kellyjonbrazil/jc/pull/447 works with a slight tweak. Would like to discuss in the PR when you get a chance. Thanks!

**Comment by kellyjonbrazil** [comment]
I've merged in the fix and this will be included in the next release.

**Comment by kellyjonbrazil** [comment]
Added in v1.23.5
