### ISSUE TITLE
`Exit due to unexpected error:` when pygments not installed

### ISSUE THREAD

**Issue by oliverkurth** [kellyjonbrazil/jc#471]
This is a minor issue, but I thought worth reporting anyway and I spent some time getting the root cause: when `pygments` is not installed, `jc` will throw this error:

```
# ls -l | jc --ls
jc:  Error - Exit due to unexpected error:
             NameError: name 'Name' is not defined
```
With `--debug`:
```
# jc --debug
Traceback (most recent call last):
  File "/usr/bin/jc", line 33, in <module>
    sys.exit(load_entry_point('jc==1.23.4', 'console_scripts', 'jc')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/jc/cli.py", line 890, in main
    JcCli().run()
  File "/usr/lib/python3.11/site-packages/jc/cli.py", line 872, in run
    self._run()
  File "/usr/lib/python3.11/site-packages/jc/cli.py", line 796, in _run
    self.set_custom_colors()
  File "/usr/lib/python3.11/site-packages/jc/cli.py", line 170, in set_custom_colors
    Name.Tag: f'bold {PYGMENT_COLOR[color_list[0]]}' if color_list[0] != 'default' else f"bold {PYGMENT_COLOR['blue']}",   # key names
    ^^^^
NameError: name 'Name' is not defined
```

From the code at https://github.com/kellyjonbrazil/jc/blob/master/jc/cli.py#L30C1-L40C9 it looks like `jc` is supposed to work without `pygments`:
```
PYGMENTS_INSTALLED: bool = False
try:
    import pygments
...
    PYGMENTS_INSTALLED = True
except Exception:
    pass
```
But it fails anyway, with the hard to debug error.

It happened for me because I was creating an RPM package, but forgot to add `python3-pygments` to the requirements.

**Comment by kellyjonbrazil** [comment]
I have this fixed in the `dev` branch and this will make it in the next release.

**Comment by kellyjonbrazil** [comment]
Added in v1.23.5
