### ISSUE TITLE
`runtests.sh` fails when run inside a container

### ISSUE THREAD

**Issue by oliverkurth** [kellyjonbrazil/jc#474]
`runtests.sh` throws errors when run inside a container. Most (not all I think) seem to be related to the `epoch`. Here is the end of the output, showing an example:
```
======================================================================
FAIL: test_who_ubuntu_18_4 (tests.test_who.MyTests)
Test 'who' on Ubuntu 18.4
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/jc/tests/test_who.py", line 73, in test_who_ubuntu_18_4
    self.assertEqual(jc.parsers.who.parse(self.ubuntu_18_4_who, quiet=True), self.ubuntu_18_4_who_json)
AssertionError: Lists differ: [{'us[69 chars]1583117520}, {'user': 'kbrazil', 'tty': 'pts/0[71 chars]640}] != [{'us[69 chars]1583146320}, {'user': 'kbrazil', 'tty': 'pts/0[71 chars]440}]

First differing element 0:
{'use[16 chars]tty': 'ttyS0', 'time': '2020-03-02 02:52', 'epoch': 1583117520}
{'use[16 chars]tty': 'ttyS0', 'time': '2020-03-02 02:52', 'epoch': 1583146320}

- [{'epoch': 1583117520,
?                 ^^^

+ [{'epoch': 1583146320,
?                 ^^^

    'time': '2020-03-02 02:52',
    'tty': 'ttyS0',
    'user': 'kbrazil'},
-  {'epoch': 1583117640,
?                 ^^

+  {'epoch': 1583146440,
?                 ^ +

    'from': '192.168.71.1',
    'time': '2020-03-02 02:54',
    'tty': 'pts/0',
    'user': 'kbrazil'}]

----------------------------------------------------------------------
Ran 1355 tests in 36.051s

FAILED (failures=150, errors=4)
```

To reproduce, run a Ubuntu container (`docker run -ti --rm ubuntu`), install the requirements, clone and test:
```
apt install python3 python3-ruamel.yaml python3-xmltodict python3-pygments git
git clone https://github.com/kellyjonbrazil/jc.git
cd jc
./runtests.sh
```
Same test runs fine in a Ubuntu 22.04 or Photon 5.0 VM. I see the same issue in a Photon 5.0 container, so it looks like some issue with that.

Log output attached.

[runtests.log](https://github.com/kellyjonbrazil/jc/files/13065329/runtests.log)

**Comment by kellyjonbrazil** [comment]
Hi there - this seems to be timezone related. The test machine must be set to the Pacific timezone (`America/Los_Angeles`). Are tests still failing with the correct timezone?

**Comment by kellyjonbrazil** [comment]
As a point of reference, here is the configuration for GitHub actions, which I believe runs the test in a container:

https://github.com/kellyjonbrazil/jc/blob/master/.github/workflows/pythonapp.yml

**Comment by oliverkurth** [comment]
Okay, got it. Looks like I was lucky because I live in that time zone, so that is why it worked in the VMs.

```
apt install tzdata -y
```
That prompts me for the time zone.

Most of the tests succeed now, but I am still getting this:
```
======================================================================
ERROR: test_xml_cd_catalog (tests.test_xml.MyTests)
Test the cd catalog xml file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/jc/tests/test_xml.py", line 51, in test_xml_cd_catalog
    self.assertEqual(jc.parsers.xml.parse(self.generic_xml_cd_catalog, quiet=True), self.generic_xml_cd_catalog_json)
  File "/root/jc/jc/parsers/xml.py", line 159, in parse
    return _process(data, has_data)
  File "/root/jc/jc/parsers/xml.py", line 113, in _process
    proc_output = xmltodict.parse(proc_data,
  File "/usr/lib/python3/dist-packages/xmltodict.py", line 291, in parse
    handler = _DictSAXHandler(namespace_separator=namespace_separator,
TypeError: _DictSAXHandler.__init__() got an unexpected keyword argument 'process_comments'

======================================================================
ERROR: test_xml_foodmenu (tests.test_xml.MyTests)
Test the food menu xml file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/jc/tests/test_xml.py", line 57, in test_xml_foodmenu
    self.assertEqual(jc.parsers.xml.parse(self.generic_xml_foodmenu, quiet=True), self.generic_xml_foodmenu_json)
  File "/root/jc/jc/parsers/xml.py", line 159, in parse
    return _process(data, has_data)
  File "/root/jc/jc/parsers/xml.py", line 113, in _process
    proc_output = xmltodict.parse(proc_data,
  File "/usr/lib/python3/dist-packages/xmltodict.py", line 291, in parse
    handler = _DictSAXHandler(namespace_separator=namespace_separator,
TypeError: _DictSAXHandler.__init__() got an unexpected keyword argument 'process_comments'

======================================================================
ERROR: test_xml_nmap (tests.test_xml.MyTests)
Test nmap xml output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/jc/tests/test_xml.py", line 63, in test_xml_nmap
    self.assertEqual(jc.parsers.xml.parse(self.generic_xml_nmap, quiet=True), self.generic_xml_nmap_json)
  File "/root/jc/jc/parsers/xml.py", line 159, in parse
    return _process(data, has_data)
  File "/root/jc/jc/parsers/xml.py", line 113, in _process
    proc_output = xmltodict.parse(proc_data,
  File "/usr/lib/python3/dist-packages/xmltodict.py", line 291, in parse
    handler = _DictSAXHandler(namespace_separator=namespace_separator,
TypeError: _DictSAXHandler.__init__() got an unexpected keyword argument 'process_comments'

======================================================================
ERROR: test_xml_nmap_r (tests.test_xml.MyTests)
Test nmap xml raw output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/jc/tests/test_xml.py", line 69, in test_xml_nmap_r
    self.assertEqual(jc.parsers.xml.parse(self.generic_xml_nmap, raw=True, quiet=True), self.generic_xml_nmap_r_json)
  File "/root/jc/jc/parsers/xml.py", line 148, in parse
    raw_output = xmltodict.parse(data,
  File "/usr/lib/python3/dist-packages/xmltodict.py", line 291, in parse
    handler = _DictSAXHandler(namespace_separator=namespace_separator,
TypeError: _DictSAXHandler.__init__() got an unexpected keyword argument 'process_comments'

----------------------------------------------------------------------
Ran 1355 tests in 6.709s

FAILED (errors=4)
```

**Comment by oliverkurth** [comment]
This also works, in case the time zone is different and you don't want to switch globally:
```
TZ=America/Los_Angeles ./runtests.sh
```
`tzdata` needs to be installed though.

The xml errors I see in the Ubuntu container may be related to the `xmltodict` version in Ubuntu (0.12.0-2). The tests run fine in a Photon 5.0 container (with latest `xmltodict`, 0.13.0) when I install `tzdata` and run the tests as above.

**Comment by kellyjonbrazil** [comment]
Ah that brings up a good point - I may need to update the requirements.txt because I added comments processing functionality for xml in this latest version. I think `jc` works fine since it will just try again without comment processing if it fails but I may need to update the tests, too. I’ll look into it.

**Comment by kellyjonbrazil** [comment]
I added a fix to the XML parser in `dev`. Could you try swapping it out and see if that works for you? If so, I'll release a new version today with the fix:

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/xml.py

**Comment by oliverkurth** [comment]
Thanks for fixing - but it's still not working. Now I am getting these errors:
```
======================================================================
FAIL: test_xml_nmap (tests.test_xml.MyTests)
Test nmap xml output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/jc/tests/test_xml.py", line 63, in test_xml_nmap
    self.assertEqual(jc.parsers.xml.parse(self.generic_xml_nmap, quiet=True), self.generic_xml_nmap_json)
AssertionError: {'nmaprun': {'@scanner': 'nmap', '@args': '[1399 chars]'}}}} != {'#comment': 'Nmap 7.92 scan initiated Wed [1505 chars]'}}}}
Diff is 3307 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_xml_nmap_r (tests.test_xml.MyTests)
Test nmap xml raw output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/jc/tests/test_xml.py", line 69, in test_xml_nmap_r
    self.assertEqual(jc.parsers.xml.parse(self.generic_xml_nmap, raw=True, quiet=True), self.generic_xml_nmap_r_json)
AssertionError: {'nmaprun': {'_scanner': 'nmap', '_args': '[1399 chars]'}}}} != {'#comment': 'Nmap 7.92 scan initiated Wed [1505 chars]'}}}}
Diff is 3307 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 1355 tests in 6.551s

FAILED (failures=2)
```

I tried first by checking out 3cd2dce496fff1c45e888cd6b971fc1cbc15f755 , then just copying the raw file as instructed. Same error.

```
root@f98d501dd60f:~/jc# dpkg -l python3-xmltodict
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name              Version      Architecture Description
+++-=================-============-============-=====================================================================
ii  python3-xmltodict 0.12.0-2     all          Makes working with XML feel like you are working with JSON (Python 3)
root@f98d501dd60f:~/jc# date
Mon Oct 23 09:20:12 PDT 2023
root@f98d501dd60f:~/jc# 
```

**Comment by kellyjonbrazil** [comment]
Thanks for testing - that is actually a good error and means the fix worked but I need to update my tests for occaisions when the xml2dict library is old. I'll work on that now.

**Comment by kellyjonbrazil** [comment]
I have made the changes to the `dev` branch. It's a little more involved than a couple of files - not sure if you can build/test from dev and let me know if everything looks ok now?

**Comment by oliverkurth** [comment]
Just pulled from `dev` and it works now! Thank you!
```
Ran 1355 tests in 6.715s

OK
```

**Comment by kellyjonbrazil** [comment]
Added in v1.23.6
